### ISSUE TITLE
Event Categories do not load right away when panel opens

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#11]
When I open the Event Category panel in the sidebar, it takes a noticeably long amount of time for the existing categories to actually show up. Example gif: http://p.tri.be/vTfoDr

**Comment by leahkoerper** [comment]
Tags are having a similar delayed behavior when adding a new one.

**Comment by bordoni** [comment]
That is normal, default behavior from Gutenberg, they might need to add an Spinner there to indicate that it's loading the files. Should we add a Pull Request to add that?

We don't create those metaboxes, all WordPress Gutenberg.

**Comment by leahkoerper** [comment]
After we get first version of the extension out, yes, that would be a good PR.

**Comment by bordoni** [comment]
We fixed that issue on the latest version `0.2.4-alpha` alongside a change in Gutenberg code made this more stable for us.
