### ISSUE TITLE
Notice says Post Published/Updated instead of Event

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#13]
It should of course say Event Published or Event Updated. Everywhere else looks correct.
http://p.tri.be/4mbB0F

**Comment by bordoni** [comment]
We cannot change that for now. Gutenberg doens't allow changing that, we might want to tinker with it or Pull Request for that to follow the WordPress Post Type Labels.

**Comment by leahkoerper** [comment]
Okay, no worries. Not a big deal right now :)

**Comment by bordoni** [comment]
This was solved by Issue by Gutenberg crew.
