### ISSUE TITLE
Event blocks should only be available on Event CPT

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#22]
Right now Event blocks are available on other post types, and even in the quick add element. All Event blocks should be limited to the Event post type.

![Dev](https://user-images.githubusercontent.com/6052209/37068969-33038e2e-2166-11e8-9833-bb60a3f0503f.png)

**Comment by bordoni** [comment]
Unfortunately that doesn't seem possible right now, but I will dig more to see if we can do that.

**Comment by leahkoerper** [comment]
I would really like to fix this for R1. @bordoni could you maybe add to https://github.com/WordPress/gutenberg/issues/2685 and see if we can make this happen? Or might the solution suggested by youknowriad work for us?

**Comment by leahkoerper** [comment]
@bordoni will we now be able to finish this task, with https://github.com/WordPress/gutenberg/pull/6208 merged?

**Comment by bordoni** [comment]
As seen below we are no longer facing this bug.
<img width="911" alt="screen shot 2018-07-25 at 09 44 52" src="https://user-images.githubusercontent.com/236579/43201626-694b4542-8fef-11e8-9bed-55158530fc7c.png">
