### ISSUE TITLE
Export Links block UI needs improvement

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#25]
Noticing multiple things:
1. Backend/admin does not show the button styles, just links
2. Admin side shows the two stacked instead of horizontal like on FE
3. User cannot select the end or middle of the text, only start typing (to change label)

![screen capture on 2018-03-06 at 12-37-01](https://user-images.githubusercontent.com/236579/37068596-41123146-218e-11e8-9417-e51ea3f02464.gif)

**Comment by leahkoerper** [comment]
With reload I'm now seeing button styles better. Text on unchanged one is illegible (https://cloudup.com/c4k9Lkw8AAB). In this case I don't think we need to do different colors for default and non-default text.

**Comment by leahkoerper** [comment]
@bordoni this is better but problem 3 from above is still weird:
> User cannot select the end or middle of the text, only start typing (to change label)

I can open another issue for that- it's less important.

**Comment by bordoni** [comment]
Ohh it's becasue both of them are not actual Text they are just a placeholder. Default Placeholder behavior for browsers. I mean, the idea if the person will add anything there it will be a completely new string.

**Comment by leahkoerper** [comment]
Okay! We're all good then.
