### ISSUE TITLE
Switching back to Classic Editor can leave wonky HTML

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#26]
If I play with an event in the Block Editor and then later load the same event in the Classic Editor, overall it works nicely. However, it does leave some HTML in the description box. This HTML remains even if I deactivate our Gutenberg extension.

| Classic Visual | Classic HTML |
| --- | --- |
| ![Classic Editor](https://cldup.com/Sflxh5RiSO-3000x3000.png) | ![Classic Editor](https://cldup.com/RwyynGISnw-3000x3000.png) |

**Comment by bordoni** [comment]
Not our fault, maybe a bug we need to report to Gutenberg.

**Comment by leahkoerper** [comment]
@bordoni this might be related: https://github.com/WordPress/gutenberg/issues/6385

**Comment by bordoni** [comment]
We no longer facing this issues. Tested:
http://i.bordoni.me/tDKm
