### ISSUE TITLE
Venue Block: phone and website do not show in admin

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#27]
On the admin side, the phone and website for my venue do not display in the block. They do display properly on the front end.

| Backend | Frontend |
| :---: | :---: |
| ![image](https://user-images.githubusercontent.com/236579/37068083-b8c417d4-218b-11e8-89b4-1d43b21bb003.png) |  ![image](https://user-images.githubusercontent.com/236579/37068099-c7ecbba8-218b-11e8-9bf9-3ae1d7a45903.png) |

**Comment by bordoni** [comment]
Not our fault, maybe a bug we need to report to Gutenberg.

**Comment by leahkoerper** [comment]
Fixed!
