### ISSUE TITLE
Google Map Link only shows in admin, not FE

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#28]
For the Venue block, the + Show Google Map link shows on the backend admin but not on the FE display.

| Admin | Frontend |
| --- | --- |
| ![Admin](https://user-images.githubusercontent.com/6052209/37068888-d7a736d4-2165-11e8-86f8-aa825a346ccb.png) | ![Frontend](https://user-images.githubusercontent.com/6052209/37068870-bdb3bcfc-2165-11e8-9c74-fe52b23fd642.png) |

**Comment by bordoni** [comment]
That is due to how we currenty don't have the filtering for Google Maps Embed and Link on Gutenberg.

So I am switching this to a feature, which I need to implement as a block setting.

**Comment by bordoni** [comment]
Added this feature, by using the Block Sidebar to have data there.
| Block Sidebar |
| :---: |
| ![GIF](http://i.bordoni.me/q6DA/download/Screen%20Recording%202018-03-11%20at%2007.47.gif) |

**Comment by leahkoerper** [comment]
Beautiful!
