### ISSUE TITLE
[0.2.7-alpha] cannot set a time later than the current hour and cannot add organizer or venue

### ISSUE THREAD

**Issue by designsimply** [moderntribe/events-gutenberg#309]
First, thank you for working on Gutenberg blocks!

I tried testing the 0.2.7 alpha version of the Events Gutenberg extension and ran into a few issues. I am noting them in one go here but if you would like the issues split out into smaller ones, please let me know.

1. Install Gutenberg 3.8.0.
1. Install The Events Calendar 4.6.23.
1. Install Events Gutenberg 0.2.7-alpha.
1. Go to Events > Add New.
1. Note the following error in the browser console: `Jed localization error: Error: Domain `events-gutenberg` was not found.` and `TypeError: "e is undefined"`
1. Note that the Event Price block shows an error on screen: "This block has encountered an error and cannot be previewed."
1. Change the date and time.
1. Note that the time cannot be set later than the current hour.
1. Add a description.
1. Add an event organizer.
1. Add a venue.
1. Publish the event.
1. Re-open the event for editing (note the view is different).
1. Try adjusting the date and time.
1. Try adding a website under Details.
1. Try adding a venue.
1. Click the "Update" button for the post.
1. Go back to try to view the changes just saved.

<strong>Result:</strong> cannot set a time later than the current hour, the event price block shows an error, adding an organizers or venue doesn't seem to work via the block interface. The blocks also overlap in a way that makes them a bit hard to work with. ([8m30s](https://cloudup.com/cMbKtIgktrh))

<img src="https://user-images.githubusercontent.com/1119271/45455160-667a0f80-b6a3-11e8-80be-9185c8372a3f.png" width="400">
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14929&action=edit running WordPress 4.9.8, Gutenberg 3.8.0, The Events Calendar 4.6.23, and Events Gutenberg 0.2.7-alpha using Firefox 62.0 on macOS 10.13.6.</sup>

Errors that show up in the browser console after going to Events > Add New:

> Jed localization error: Error: Domain `events-gutenberg` was not found.
> index.js:5:18586

> Unhandled promise rejection TypeError: "items is undefined"
> es6.promise.js:110

Error in the browser console after re-editing and clicking the "Create Organizer" button:

> Unhandled promise rejection TypeError: "items is undefined"

There were also a few noteworthy warnings in the browser console:

> value prop in color objects passed by withColors HOC is deprecated and will be removed from Gutenberg in 3.9. Please use `color` prop passed in the object instead. Note: This is a global warning, shown regardless of whether value prop is used.
> wp.editor.RichTextProvider is deprecated and will be removed from Gutenberg in 4.0.0. Please use wp.data.select( 'core/editor' ) methods instead. Note: This is a global warning, shown regardless of whether the component is used.

To see a list of deprecations, go to https://wordpress.org/gutenberg/handbook/reference/deprecated/#3-8-0

Note: the Date Format in my Events > Settings > Display page are the defaults ([screenshot](https://user-images.githubusercontent.com/1119271/45454845-72190680-b6a2-11e8-96d6-cde65d8a378e.png)).

**Comment by designsimply** [comment]
Thanks! It's exactly the Gutenberg 3.8 pre-release testing where it was suggested that testers may want to help out with the Events Gutenberg plugin 😊 https://make.wordpress.org/test/2018/09/05/call-for-testing-gutenberg-3-8-pre-release/

Please feel free to chime in there with a comment if you'd like help testing again after your new release is out.

**Comment by bordoni** [comment]
For sure, that helps a lot @designsimply , thanks again.

I saw that was going to happen, I think someone mentioned it on the last week's chat on #core-editor chat.

Also will comment there soon, I just saw your comment about the "Alpha" stage.
> Like Gutenberg, this should be only be activated on a test site or local install. 

I will talk internally with the team so we can make some changes to possibly change that soonish.
