### ISSUE TITLE
Multi-Day Toggle in Gutenberg

### ISSUE THREAD

**Issue by campmedia** [moderntribe/events-gutenberg#316]
The Multi-Day Toggle doesn't toggle on to display an end date selector.

By reverting to the classic editor, the end date can be selected, then switching to the Gutenberg editor renders the multi-day toggle ON and the second date selector field also visible.

**Comment by mitogh** [comment]
Thanks for your report @campmedia, we have flagged this one internally as well and we plan to send a fix in the upcoming release for this problem.

Will keep this issue opened and let you know as soon as we have a fix on `master` and latest release available.

Thanks again for taking the time to share your report with us.

**Comment by bordoni** [comment]
hi @campmedia,

Thanks for reporting this issue to us, we solved this on the version `0.3.3-alpha`.

Hopefully it solved your problem, otherwise please let us know, we want to make sure it's no longer a bug.
