### ISSUE TITLE
Event blocks try to wrap in admin and FE

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#37]
Various blocks are "trying" to wrap as I add other Gutenblocks and edit the event. Sometimes they wrap on FE and other times it's in the admin. For now, all our stuff should maintain its full width layout so we can keep the layer-cake style reordering. I want to avoid wrapping until R3 when we can do it right.
<img width="989" alt="screen shot 2018-03-07 at 3 28 37 pm" src="https://user-images.githubusercontent.com/6052209/37124241-4e2c7506-221c-11e8-8538-77c3c6403f6a.png">
<img width="866" alt="screen shot 2018-03-07 at 3 28 55 pm" src="https://user-images.githubusercontent.com/6052209/37124246-52ed0a2e-221c-11e8-8d84-8b50bb25d3c6.png">

**Comment by bordoni** [comment]
Ohh ok, that is a CSS bug. Good catch.

**Comment by leahkoerper** [comment]
This is better, but there's still some funkiness especially with standard image blocks and/or with our event sharing block. That said, some of the behavior also makes me think that it might be more in core than our blocks.

![Image inside venue block](https://user-images.githubusercontent.com/6052209/37181340-630af68a-22e1-11e8-971c-630b68f069d5.png)

| Admin | Frontend |
| --- | --- |
| ![Admin](https://cldup.com/4AIVrTer3w-2000x2000.png) | ![Frontend](https://cldup.com/cmssgK_gcS.thumb.png) |

**Comment by leahkoerper** [comment]
I'm full of shit- this is totally fixed I just needed to pull the latest code. Amazing what a difference it makes!
