### ISSUE TITLE
Incorrect date displayed in single event's page

### ISSUE THREAD

**Issue by piotrkulpinski** [moderntribe/events-gutenberg#370]
Hi, 

I've noticed that single event's page shows current date instead of the proper event's date.

Here's a date set in WordPress admin:
![image](https://user-images.githubusercontent.com/358412/46603141-81993d00-caf2-11e8-88d4-2230dab832b2.png)

And here's the same event rendered on the site: 
![image](https://user-images.githubusercontent.com/358412/46603165-91b11c80-caf2-11e8-8769-a3057adcbb8a.png)

Cheers, Piotrek

**Comment by bordoni** [comment]
Hi @piotrkulpinski,

Thanks for reporting this bug to us, just to double check with you. What is the version of the extension and Gutenberg Plugin you are using?

We will tackle this one on version `0.3.1-alpha` that should come out later this week.

My Best Regards,

**Comment by piotrkulpinski** [comment]
@bordoni 

The Events Calendar: 4.6.24
The Events Calendar PRO: 4.4.33
The Events Calendar: Gutenberg Extension: 0.2.8-alpha
Gutenberg: 3.9.0

Thanks for looking into it!

**Comment by piotrkulpinski** [comment]
Just checked and the issue is still there with 0.3.0-alpha

**Comment by AnneSteen** [comment]
Hello,

I am also using 0.3.1-alpha, Gutenberg 4.0.0, Events Calendar 4.6.24.1, Events Calendar Pro 4.4.33, and the date/time for a single event self-corrects to the current date/time I update/publish the listing. I hope this information is helpful.

**Comment by bordoni** [comment]
Hi @AnneSteen and @piotrkulpinski,

On version `0.3.3-alpha` I think we did solve this problem.

I would love to hear back from you guys if that isn't the case, we want to make sure we are solving as many bugs as possible before WP 5.0 is live.
