### ISSUE TITLE
Date in event blocks should follow Display settings date format

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#38]
The date format in the Event Subtitle Classic block and Event Details Classic block should obey the date format set by the admin in Events --> Settings --> Display. 

<img width="914" alt="screen shot 2018-03-08 at 3 10 21 pm" src="https://user-images.githubusercontent.com/6052209/37181687-dd7398ae-22e2-11e8-8d80-2a872c9f6ece.png">

**Comment by leahkoerper** [comment]
If this ends up being a bigger lift than you thought, a good iterative step would be having the blocks respect the date format set in the general WP settings.

**Comment by bordoni** [comment]
Based on User Interface suggested by Rachel and @roboticarm we will be splitting these fields to allow more flexibility. So I've already started the work for that on #40 as well as solve the Settings request above.

**Comment by leahkoerper** [comment]
Looks good!
