### ISSUE TITLE
Issue with selection of venue

### ISSUE THREAD

**Issue by hagege** [moderntribe/events-gutenberg#408]
Hi,
there seem to be an issue when I choose a venue: If you enter a part of the desired venue, the correct venue will appear. But if you click on this location, it will not be taken over, but the field will remain empty. Activated is Gutenberg 4.0.0 and The Events Calendar: Gutenberg Extension 0.3.1

![image](https://user-images.githubusercontent.com/27292550/47180280-7fb85080-d320-11e8-83bb-47d330b1fb7b.png)

Best Regards,
Hans-Gerd

**Comment by bordoni** [comment]
Hi @hagege,

We solved that issue on version `0.3.3-alpha`.

Sorry for the delayed answer.
