### ISSUE TITLE
Embeds are not working as expected

### ISSUE THREAD

**Issue by gravnetic** [moderntribe/events-gutenberg#42]
I went ahead and used it on a live site, but not on a live event.  It worked well, not perfect but it's really cool!  I think one issue that is Gutenberg related is hiding post options doesn't work when switching and there is not a way to hide 'tags' for example.  I don't use tag filters so I typically hide them but there doesn't appear to be a way to do this.

More to your plugin, video embeds don't work as expected at all.  Here is a link of a basic video embed not really working well.  https://jaypetervary.com/event/the-cyclist-menu-arizona/

**Comment by zbtirrell** [comment]
Not sure the exact cause, but this CSS makes your video appear:
```
div.ast-oembed-container {
	position:static;
}
```

**Comment by bordoni** [comment]
That was an issue on Gutenberg at the time. I think it's now fixed. @gravnetic would you mind confirming? Otherwise I will close the ticket next Tuesday.
