### ISSUE TITLE
The Events Calendar: Gutenberg Extension

### ISSUE THREAD

**Issue by ThianBrodie** [moderntribe/events-gutenberg#518]
Hey Guys, I have a problem, it would not install through the Wordpress installer, so I uploaded it via ftp, I can not test it as it will not activate.
![test](https://user-images.githubusercontent.com/13458710/49344385-3755b780-f66e-11e8-8ad2-4257d7a72594.jpg)

**Comment by bordoni** [comment]
Hi @ThianBrodie,
On our latest version of The Events Calendar, we included the latest version of the Extension with a lot of new Bugfixes and some new features.

For now, we are no longer supporting the Gutenberg Extension, only the WordPress 5.0 included Blocks Editor, which is a very similar codebase but has some incompatibilities with our code that we are trying to fix.

When you activate the latest version of The Events Calendar with WP 5.0 or bigger, you will see a new Option on your Settings Page of Events, to activate Events on the Blocks Editor.

My Best Regards,
