### ISSUE TITLE
Event Details Classic - focus shows duplicated menu items and no labels

### ISSUE THREAD

**Issue by leahkoerper** [moderntribe/events-gutenberg#53]
When I click into the Event Details Classic block, I see duplicated icons in the block menu for font weights and the default labels (Details, Organizer) disappear and there is only a blank input field.
<img width="866" alt="screen shot 2018-04-19 at 10 21 13 am" src="https://user-images.githubusercontent.com/6052209/39007789-a71ff6ae-43bb-11e8-82d6-3cb30f2675ef.png">

If I type in a custom label, it remains showing when I focus on the block. The labels should always show, regardless of whether or not they've been updated.

**Comment by bordoni** [comment]
As seen here, this is no longer an issue:
<img width="1022" alt="screen shot 2018-07-25 at 09 40 19" src="https://user-images.githubusercontent.com/236579/43201419-cfecc7cc-8fee-11e8-8b65-35875cfa6704.png">
