### ISSUE TITLE
missing TEC admin views, wrong permissions

### ISSUE THREAD

**Issue by chronicole** [moderntribe/events-gutenberg#7]
*SETUP*
<pre>
WORDPRESS VERSION
4.9.4
PHP VERSION
7.1.12
PLUGINS
Debug Bar version 0.9 by wordpressdotorg(https://wordpress.org/)
The Events Calendar: Gutenberg Extension version 0.1.0-alpha.1 by Modern Tribe, Inc.(https://github.com/moderntribe/events-gutenberg)
Gutenberg version 2.3.0 by Gutenberg Team
The Events Calendar version 4.6.11.1 by Modern Tribe, Inc.(http://m.tri.be/1x)
COMMON LIBRARY VERSION
4.7.8
</pre>

 *REPO*        | *BRANCH*          | *LAST COMMIT*  
------------ | ------------- | -------------
 the-event-calendar      | `bucket/gutenberg` | `32d735a` 
 gutenberg      | `master` | `3fc70e7`
 events-gutenberg      | `master` | `66c7d83` 

*ISSUE*
The TEC dashboard items aren't there, see http://p.tri.be/wmny4H. I did `yarn install` and `yarn build dev` on both gutenberg and events-gutenberg plugins. If I try to go to the URL path for something like creating a new event I see http://p.tri.be/txlm2M, but I'm logged in with the administrator account (only account there is on this install). Missing the following admin pages:

Events
Add New
Events Categories
Venues
Organizers
Import

**Comment by bordoni** [comment]
On this one, it seems like it's a bug due to not having ran `git submodule update --init --recursive`

**Comment by chronicole** [comment]
If that is ran on TEC, I did it and has no impact.

**Comment by chronicole** [comment]
This was related to a known issue with TEC and submodules and not related to extensions. I deactivated and then activated TEC and all functionality was present for TEC.
